### ISSUE TITLE
Install error: Neither directory contains a build file meson.build.

### ISSUE THREAD

**Issue by Arsca** [astroidmail/homebrew-astroid#16]
Hi,
Trying to install on OSX 10.12.6 Sierra, but it ends on the following error:

> ➜  ~  brew install astroid
...
==> Installing astroid from astroidmail/astroid
==> Downloading https://github.com/astroidmail/astroid/archive/v0.9.1.tar.gz
Already downloaded: /Users/arsca/Library/Caches/Homebrew/astroid-0.9.1.tar.gz
==> meson build --prefix=/usr/local/Cellar/astroid/0.9.1 -Ddisable-embedded-editor=true -Ddisable-plugins=true -Ddisable-tests=true
Last 15 lines from /Users/arsca/Library/Logs/Homebrew/astroid/01.meson:
2017-11-12 07:42:59 -0600
meson
build
--prefix=/usr/local/Cellar/astroid/0.9.1
-Ddisable-embedded-editor=true
-Ddisable-plugins=true
-Ddisable-tests=true
Error during basic setup:
Neither directory contains a build file meson.build.
...

**Comment by gauteh** [comment]
Arsca writes on november 12, 2017 14:51:
> Hi,
> Trying to install on OSX 10.12.6 Sierra, but it ends on the following error:
> 
>> ➜  ~  brew install astroid
> ...
> ==> Installing astroid from astroidmail/astroid
> ==> Downloading https://github.com/astroidmail/astroid/archive/v0.9.1.tar.gz
> Already downloaded: /Users/arsca/Library/Caches/Homebrew/astroid-0.9.1.tar.gz
> ==> meson build --prefix=/usr/local/Cellar/astroid/0.9.1 -Ddisable-embedded-editor=true -Ddisable-plugins=true -Ddisable-tests=true
> Last 15 lines from /Users/arsca/Library/Logs/Homebrew/astroid/01.meson:
> 2017-11-12 07:42:59 -0600
> meson
> build
> --prefix=/usr/local/Cellar/astroid/0.9.1
> -Ddisable-embedded-editor=true
> -Ddisable-plugins=true
> -Ddisable-tests=true
> Error during basic setup:
> Neither directory contains a build file meson.build.
> ...

You are trying to install an old version of astroid.

**Comment by Arsca** [comment]
Actually I'm trying to install it according to the README.md
> $ brew tap astroidmail/astroid
> $ brew install astroid

Is this a staled repo?

**Comment by gauteh** [comment]
Arsca writes on november 12, 2017 16:41:
> Actually I'm trying to install it according to the README.md
>> $ brew tap astroidmail/astroid
>> $ brew install astroid
> 
> Is this a staled repo?

Not very I think. But if you use latest version or git version the formula 
should hopefully work.

**Comment by yeled** [comment]
add `--HEAD`

**Comment by Arsca** [comment]
@yeled Thanks, it seems to get past the previous error, but get now an error related to Boost library 'thread' even if the library is installed:

>➜ brew install --HEAD astroid
==> Installing astroid from astroidmail/astroid
==> Cloning https://github.com/astroidmail/astroid.git
Cloning into '/Users/arsca/Library/Caches/Homebrew/astroid--git'...
remote: Counting objects: 239, done.
remote: Compressing objects: 100% (223/223), done.
remote: Total 239 (delta 16), reused 86 (delta 6), pack-reused 0
Receiving objects: 100% (239/239), 3.26 MiB | 709.00 KiB/s, done.
Resolving deltas: 100% (16/16), done.
==> Checking out branch master
==> meson build --prefix=/usr/local/Cellar/astroid/HEAD-4d1e52b -Ddisable-embedded-editor=true -Ddisable-plugins=true -Ddisable-tests=true
Last 15 lines from /Users/arsca/Library/Logs/Homebrew/astroid/01.meson:
Build dir: /private/tmp/astroid-20171112-88735-wawcx3/build
Build type: native build
Project name: astroid
Native C compiler: clang (clang 9.0.0)
Native C++ compiler: clang++ (clang 9.0.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/local/opt/pkg-config/bin/pkg-config (0.29.2)
Native dependency gmime-3.0 found: YES 3.0.3
Dependency gmime-2.6 found: NO
Meson encountered an error in file meson.build, line 23, column 0:
Requested Boost library 'thread' not found

**Comment by yeled** [comment]
this needs a meson downgrade sadly. we'll need to move to cmake asap for OS X

**Comment by gauteh** [comment]
https://github.com/astroidmail/astroid/pull/428

**Comment by yeled** [comment]
@Arsca do you want to try --HEAD again?

**Comment by Arsca** [comment]
@yeled It still snags...

```
...
==> Installing astroidmail/astroid/astroid --HEAD
==> Cloning https://github.com/astroidmail/astroid.git
Cloning into '/Users/arsca/Library/Caches/Homebrew/astroid--git'...
remote: Counting objects: 242, done.
remote: Compressing objects: 100% (227/227), done.
remote: Total 242 (delta 16), reused 87 (delta 6), pack-reused 0
Receiving objects: 100% (242/242), 3.27 MiB | 756.00 KiB/s, done.
Resolving deltas: 100% (16/16), done.
==> Checking out branch master
==> cmake -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr/local/Cellar/astroid/HEAD-80253d2 -DDISABLE_EMBEDDED_EDITOR:BOOL=OFF -DDISABLE_LI
==> cmake --build build --target install
Last 15 lines from /Users/arsca/Library/Logs/Homebrew/astroid/02.cmake:
dyld: Symbol not found: _UCNV_FROM_U_CALLBACK_ESCAPE_59
  Referenced from: /usr/local/opt/webkitgtk@2.4.11/lib/libwebkitgtk-3.0.0.dylib
  Expected in: flat namespace
 in /usr/local/opt/webkitgtk@2.4.11/lib/libwebkitgtk-3.0.0.dylib
Command '['/tmp/astroid-20171207-17169-1gd4g13/build/gir_main', u'--introspect-dump=/tmp/tmp-introspectICm5oF/functions.txt,/tmp/tmp-introspectICm5oF/dump.xml']' returned non-zero exit status -6
[56/98] Building CXX object CMakeFiles/hypocycloid.dir/src/utils/vector_utils.cc.o
[57/98] Building CXX object CMakeFiles/hypocycloid.dir/src/utils/utils.cc.o
[58/98] Building CXX object CMakeFiles/hypocycloid.dir/src/utils/gmime/gmime-compat.cc.o
[59/98] Building CXX object CMakeFiles/hypocycloid.dir/src/plugin/manager.cc.o
[60/98] Building CXX object CMakeFiles/hypocycloid.dir/src/modes/thread_view/thread_view.cc.o
[61/98] Building CXX object tests/CMakeFiles/test_generic.dir/test_generic.cc.o
[62/98] Building CXX object tests/CMakeFiles/test_convert_error.dir/test_convert_error.cc.o
[63/98] Building CXX object tests/CMakeFiles/test_crypto.dir/test_crypto.cc.o
[64/98] Building CXX object tests/CMakeFiles/test_dates.dir/test_dates.cc.o
ninja: build stopped: subcommand failed.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/astroidmail/homebrew-astroid/issues

```

**Comment by gauteh** [comment]
Could this be related to webkitgtk not being compiled against the latest icu? It is a different issue at least.

**Comment by gauteh** [comment]
Need info.
