### ISSUE TITLE
#17: make Ninja build backend a conditional mandatory requirement, and add make as a fallback.

### ISSUE THREAD

**Issue by c-alpha** [astroidmail/homebrew-astroid#18]
PR #17 makes Ninja a requirement for building astroid.

I would like to propose to make ninja an option (with default enabled). Those who don't want to install ninja just to build astroid once could then use `brew install astroid --without-ninja` to build it using `make`.

I am aware that for development work fast turn-around times are important.

But from an end-user's perspective, there is no point in unconditionally requiring a particular build tool. Considering that a make of sorts being available on any system using homebrew is a fairly safe bet, IMHO, and that cmake generates build files for many backends, ninja being just one of them, I would maintain that a make build should always remain possible as a fallback solution and as a last resort.

**Comment by yeled** [comment]
How about `-GNinja` only if you are building `--HEAD`?

**Comment by c-alpha** [comment]
Brilliant idea!
