### ISSUE TITLE
scons --disable-embeded-editor fails the build

### ISSUE THREAD

**Issue by liljenstolpe** [astroidmail/homebrew-astroid#2]
10.12.4 with updated homebrew.  All pre-requisites build.  Build of astroid fails as below:

==> Installing astroid from astroidmail/astroid
==> Downloading https://github.com/astroidmail/astroid/archive/v0.8.tar.gz
Already downloaded: /Users/cdl/Library/Caches/Homebrew/astroid-0.8.tar.gz
==> /usr/local/opt/scons/bin/scons install --propagate-environment --prefix=/usr
Last 15 lines from /Users/cdl/Library/Logs/Homebrew/astroid/01.scons:

    debug   ..:  True
    release ..:  git
    version ..:
    profile ..:  False
    libsass ..:  True
    scss .....:  sassc ( use: False )
    plugins ..:  False
    terminal .:  True
    prefix ...:  /usr/local/Cellar/astroid/0.8

scons: done reading SConscript files.
usage: scons [OPTION] [TARGET] ...

SCons Error: no such option: --disable-embedded-editor

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/astroidmail/homebrew-astroid/issues

**Comment by yeled** [comment]
It needs @gauteh to cut a new release from HEAD, then it will work.

**Comment by gauteh** [comment]
Fixed.

**Comment by liljenstolpe** [comment]
Thx
