### ISSUE TITLE
need to update libpeas reference?

### ISSUE THREAD

**Issue by c-alpha** [astroidmail/homebrew-astroid#24]
Now that [homebrew-core#22430](https://github.com/Homebrew/homebrew-core/pull/22430/) has finally been merged (hooray! 👍), it builds with python@3 support by default.

(NOTE: Previously it did build without any python support at all, so python plugins couldn't be run on macOS at all out of the box. END NOTE)

Should the astroid formula now be updated to also enable python@2 support by adding `--with-python@2`? It seems some plugins still use python@2?

**Comment by gauteh** [comment]
I think all astroid plugins are Python3
