### ISSUE TITLE
scons needs python 2

### ISSUE THREAD

**Issue by gauteh** [astroidmail/homebrew-astroid#9]
got this issue reported:
<img width="672" alt="screen shot 2017-05-13 at 10 27 01" src="https://cloud.githubusercontent.com/assets/56827/26024323/71546aee-37cf-11e7-928a-2b309c494e74.png">

older python 2 is already installed somewhere

**Comment by cpiro** [comment]
I'm not sure this a problem with astroid's formula. We use the `scons` method, which calls the executable installed by the `scons` formula. 1/ It's up to the `scons` formula to make that executable work correctly 2/ its shebang (on my system at least) is `/usr/bin/env python`, so the interpreter is whatever `python` executable is handy, which should really be Python 2. macOS ships with `python` meaning Python 2, and I'm pretty sure Homebrew is careful to install Python 3 as `python3`. If I the bug reporter runs `python --version`, does it return `Python 3.5.2`? 

```
$ cw /usr/local/opt/scons/bin/scons
/usr/local/opt/scons/bin/scons is /usr/local/opt/scons/bin/scons
/usr/local/Cellar/scons/2.5.1/libexec/scons.py
/usr/local/opt/scons/bin/scons: symbolic link to ../libexec/scons.py
/usr/local/Cellar/scons/2.5.1/libexec/scons.py: a /usr/bin/env python script text executable, ASCII text
#! /usr/bin/env python
#
# SCons - a Software Constructor
...

**Comment by gauteh** [comment]
Ah right, I thought it might needed a `python2 scons` somewhere.. maybe python was not installed via brew, but conda or something.

@patricknraanes: ping, if you have time to debug

**Comment by patnr** [comment]
Indeed, my default `python` comes from anaconda and is version 3.5. (Don't have much time today, but perhaps tomorrow)

**Comment by gauteh** [comment]
Closing, untill we get more info or the issue occurs again.
